apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: clockapp-client-dev
  name: clockapp-client-dev-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: clockapp-client-dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        Criticality: High
        Tier: frontend
        app: clockapp-client-dev
    spec:
      volumes: 
        - name: clockapp-client-dev-optionnal-var
          configMap:
            name: clockapp-client-dev-configmap
            items:
              - key: vars
                path: vars.json
      containers:
      - image: harbor.apps.dso.numerique-interieur.com/ma-tutovidea/tuto:main
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: httpd-port
          initialDelaySeconds: 10
          periodSeconds: 5
        name: clockapp-client-dev
        ports:
          - name: httpd-port
            containerPort: 8081
        readinessProbe:
          httpGet:
            path: /
            port: httpd-port
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: 900m
            memory: 1,5Gi
          requests:
            cpu: 500m
            memory: 1Gi
      imagePullSecrets:
      - name: registry-pull-secret
      restartPolicy: Always